<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="745" started-at="2022-01-29T16:23:37 UTC" finished-at="2022-01-29T16:23:37 UTC">
    <groups>
    </groups>
    <test name="SimpleLearnTest" duration-ms="414" started-at="2022-01-29T16:23:37 UTC" finished-at="2022-01-29T16:23:37 UTC">
      <class name="com.main.FirstClassInMaven">
        <test-method status="FAIL" signature="testMethod2()[pri:0, instance:com.main.FirstClassInMaven@52feb982]" name="testMethod2" duration-ms="59" started-at="2022-01-29T16:23:37 UTC" finished-at="2022-01-29T16:23:37 UTC">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.main.FirstClassInMaven.testMethod2(FirstClassInMaven.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod2 -->
        <test-method status="PASS" signature="testMethod1()[pri:0, instance:com.main.FirstClassInMaven@52feb982]" name="testMethod1" duration-ms="2" started-at="2022-01-29T16:23:37 UTC" finished-at="2022-01-29T16:23:37 UTC">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
        <test-method status="SKIP" signature="testMethod3()[pri:0, instance:com.main.FirstClassInMaven@52feb982]" name="testMethod3" duration-ms="0" started-at="2022-01-29T16:23:37 UTC" depends-on-methods="com.main.FirstClassInMaven.testMethod2" finished-at="2022-01-29T16:23:37 UTC">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method FirstClassInMaven.testMethod3()[pri:0, instance:com.main.FirstClassInMaven@52feb982] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method FirstClassInMaven.testMethod3()[pri:0, instance:com.main.FirstClassInMaven@52feb982] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod3 -->
      </class> <!-- com.main.FirstClassInMaven -->
    </test> <!-- SimpleLearnTest -->
    <test name="SimpleLearnTest1" duration-ms="6" started-at="2022-01-29T16:23:37 UTC" finished-at="2022-01-29T16:23:37 UTC">
      <class name="com.main.SecondClasa">
        <test-method status="PASS" signature="secondClassMEthod()[pri:0, instance:com.main.SecondClasa@76a3e297]" name="secondClassMEthod" duration-ms="1" started-at="2022-01-29T16:23:37 UTC" finished-at="2022-01-29T16:23:37 UTC">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- secondClassMEthod -->
      </class> <!-- com.main.SecondClasa -->
    </test> <!-- SimpleLearnTest1 -->
  </suite> <!-- Suite -->
</testng-results>
